apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
      - name: user-service-app
        image: rhounkpe/microservices-using-spring-boot-department-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9001

---

kind: Service
apiVersion: v1
metadata:
  name:  department-service-svc
spec:
  selector:
    app:  department-service-app
  ports:
  - port:  80
    targetPort:  9001